[package]
name = "asio-logger"
description = "A middleware async logger for Frame-Host."
version = "0.1.0"
authors = ["Lance Wallis <bleudeveloper@gmail.com>"]
edition = "2018"

[lib]
path = "asio-logger.rs"

[dependencies]
slog = "2.5.2"
slog-term = "2.6.0"
slog-async = "2.5.0"
