[package]
name = "frame-host"
version = "0.1.0"
authors = ["Lance Wallis <bleudeveloper@gmail.com>"]
edition = "2018"

[dependencies]
asio-logger = { path = "../asio-logger" }

serde = "1.0"
serde_json = "1.0"
