[package]
name = "asio-logger"
description = "A middleware async logger for Frame-Host."
version = "0.1.0"
authors = ["Lance Wallis <bleudeveloper@gmail.com>"]
edition = "2018"

[dependencies]
async_logger = "0.3.1"