[package]
name = "environment"
version = "0.1.0"
authors = ["Lance Wallis <bleudeveloper@gmail.com>"]
workspace = "../../"
edition = "2018"

[[bin]]
name = "environ"
path = "src/main.rs"

[dependencies]
util = { path = "../../" }
